/* The following code was generated by JFlex 1.7.0 */


import java.util.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.Integer;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/home/matiasrolon/Documentos/Universidad/2019/2do Cuatrimestre/Teoria de la Computacion I/TP Integrador/teoria1/my-app/src/main/jflex/Lexico1.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int DISPLAY = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\34\1\3\1\2\1\0\1\3\1\1\16\34\4\0\1\3\1\25"+
    "\1\7\1\0\1\32\1\0\1\30\1\0\1\40\1\41\1\6\1\44"+
    "\1\37\1\4\1\13\1\5\1\12\11\11\1\36\1\35\1\27\1\24"+
    "\1\26\2\0\1\52\1\62\1\67\1\45\1\66\1\60\1\57\1\33"+
    "\1\46\2\33\1\51\1\70\1\56\1\61\1\50\1\33\1\55\1\47"+
    "\1\54\4\33\1\53\1\33\4\0\1\32\1\0\1\21\3\33\1\17"+
    "\1\20\1\33\1\64\1\65\2\33\1\22\5\33\1\15\1\23\1\14"+
    "\1\16\1\33\1\63\3\33\1\42\1\31\1\43\1\0\41\34\1\0"+
    "\1\10\4\32\4\0\1\32\2\0\1\34\7\0\1\32\4\0\1\32"+
    "\5\0\21\32\1\33\5\32\1\0\11\32\1\33\7\32\1\33\3\32"+
    "\1\33\3\32\1\33\1\32\1\33\3\32\1\0\2\32\1\33\u01c7\32"+
    "\4\0\14\32\16\0\5\32\7\0\1\32\1\0\1\32\21\0\160\34"+
    "\5\32\1\0\2\32\2\0\4\32\1\0\1\32\6\0\1\32\1\0"+
    "\3\32\1\0\1\32\1\0\24\32\1\0\123\32\1\0\213\32\1\0"+
    "\5\34\2\0\246\32\1\0\46\32\2\0\1\32\7\0\47\32\7\0"+
    "\1\32\1\0\55\34\1\0\1\34\1\0\2\34\1\0\2\34\1\0"+
    "\1\34\10\0\33\32\5\0\3\32\15\0\6\34\5\0\1\32\4\0"+
    "\13\34\1\0\1\34\3\0\53\32\37\34\4\0\2\32\1\34\143\32"+
    "\1\0\1\32\10\34\1\0\6\34\2\32\2\34\1\0\4\34\2\32"+
    "\12\34\3\32\2\0\1\32\17\0\1\34\1\32\1\34\36\32\33\34"+
    "\2\0\131\32\13\34\1\32\16\0\12\34\41\32\11\34\2\32\4\0"+
    "\1\32\5\0\26\32\4\34\1\32\11\34\1\32\3\34\1\32\5\34"+
    "\22\0\31\32\3\34\4\0\13\32\65\0\25\32\1\0\10\32\26\0"+
    "\60\34\66\32\3\34\1\32\22\34\1\32\7\34\12\32\2\34\2\0"+
    "\12\34\1\0\20\32\3\34\1\0\10\32\2\0\2\32\2\0\26\32"+
    "\1\0\7\32\1\0\1\32\3\0\4\32\2\0\1\34\1\32\7\34"+
    "\2\0\2\34\2\0\3\34\1\32\10\0\1\34\4\0\2\32\1\0"+
    "\3\32\2\34\2\0\12\34\4\32\7\0\2\32\4\0\3\34\1\0"+
    "\6\32\4\0\2\32\2\0\26\32\1\0\7\32\1\0\2\32\1\0"+
    "\2\32\1\0\2\32\2\0\1\34\1\0\5\34\4\0\2\34\2\0"+
    "\3\34\3\0\1\34\7\0\4\32\1\0\1\32\7\0\14\34\3\32"+
    "\1\34\13\0\3\34\1\0\11\32\1\0\3\32\1\0\26\32\1\0"+
    "\7\32\1\0\2\32\1\0\5\32\2\0\1\34\1\32\10\34\1\0"+
    "\3\34\1\0\3\34\2\0\1\32\17\0\2\32\2\34\2\0\12\34"+
    "\1\0\1\32\7\0\1\32\6\34\1\0\3\34\1\0\10\32\2\0"+
    "\2\32\2\0\26\32\1\0\7\32\1\0\2\32\1\0\5\32\2\0"+
    "\1\34\1\32\7\34\2\0\2\34\2\0\3\34\10\0\2\34\4\0"+
    "\2\32\1\0\3\32\2\34\2\0\12\34\1\0\1\32\20\0\1\34"+
    "\1\32\1\0\6\32\3\0\3\32\1\0\4\32\3\0\2\32\1\0"+
    "\1\32\1\0\2\32\3\0\2\32\3\0\3\32\3\0\14\32\4\0"+
    "\5\34\3\0\3\34\1\0\4\34\2\0\1\32\6\0\1\34\16\0"+
    "\12\34\11\0\1\32\6\0\4\34\1\0\10\32\1\0\3\32\1\0"+
    "\27\32\1\0\20\32\3\0\1\32\7\34\1\0\3\34\1\0\4\34"+
    "\7\0\2\34\1\0\3\32\5\0\2\32\2\34\2\0\12\34\20\0"+
    "\1\32\3\34\1\0\10\32\1\0\3\32\1\0\27\32\1\0\12\32"+
    "\1\0\5\32\2\0\1\34\1\32\7\34\1\0\3\34\1\0\4\34"+
    "\7\0\2\34\7\0\1\32\1\0\2\32\2\34\2\0\12\34\1\0"+
    "\2\32\15\0\4\34\1\0\10\32\1\0\3\32\1\0\51\32\2\34"+
    "\1\32\7\34\1\0\3\34\1\0\4\34\1\32\5\0\3\32\1\34"+
    "\7\0\3\32\2\34\2\0\12\34\12\0\6\32\2\0\2\34\1\0"+
    "\22\32\3\0\30\32\1\0\11\32\1\0\1\32\2\0\7\32\3\0"+
    "\1\34\4\0\6\34\1\0\1\34\1\0\10\34\6\0\12\34\2\0"+
    "\2\34\15\0\60\32\1\34\2\32\7\34\4\0\10\32\10\34\1\0"+
    "\12\34\47\0\2\32\1\0\1\32\2\0\2\32\1\0\1\32\2\0"+
    "\1\32\6\0\4\32\1\0\7\32\1\0\3\32\1\0\1\32\1\0"+
    "\1\32\2\0\2\32\1\0\4\32\1\34\2\32\6\34\1\0\2\34"+
    "\1\32\2\0\5\32\1\0\1\32\1\0\6\34\2\0\12\34\2\0"+
    "\4\32\40\0\1\32\27\0\2\34\6\0\12\34\13\0\1\34\1\0"+
    "\1\34\1\0\1\34\4\0\2\34\10\32\1\0\44\32\4\0\24\34"+
    "\1\0\2\34\5\32\13\34\1\0\44\34\11\0\1\34\71\0\53\32"+
    "\24\34\1\32\12\34\6\0\6\32\4\34\4\32\3\34\1\32\3\34"+
    "\2\32\7\34\3\32\4\34\15\32\14\34\1\32\17\34\2\0\46\32"+
    "\1\0\1\32\5\0\1\32\2\0\53\32\1\0\u014d\32\1\0\4\32"+
    "\2\0\7\32\1\0\1\32\1\0\4\32\2\0\51\32\1\0\4\32"+
    "\2\0\41\32\1\0\4\32\2\0\7\32\1\0\1\32\1\0\4\32"+
    "\2\0\17\32\1\0\71\32\1\0\4\32\2\0\103\32\2\0\3\34"+
    "\40\0\20\32\20\0\126\32\2\0\6\32\3\0\u026c\32\2\0\21\32"+
    "\1\0\32\32\5\0\113\32\3\0\13\32\7\0\15\32\1\0\4\32"+
    "\3\34\13\0\22\32\3\34\13\0\22\32\2\34\14\0\15\32\1\0"+
    "\3\32\1\0\2\34\14\0\64\32\40\34\3\0\1\32\3\0\2\32"+
    "\1\34\2\0\12\34\41\0\4\34\1\0\12\34\6\0\130\32\10\0"+
    "\5\32\2\34\42\32\1\34\1\32\5\0\106\32\12\0\37\32\1\0"+
    "\14\34\4\0\14\34\12\0\12\34\36\32\2\0\5\32\13\0\54\32"+
    "\4\0\32\32\6\0\12\34\46\0\27\32\5\34\4\0\65\32\12\34"+
    "\1\0\35\34\2\0\13\34\6\0\12\34\15\0\1\32\10\0\16\34"+
    "\102\0\5\34\57\32\21\34\7\32\4\0\12\34\21\0\11\34\14\0"+
    "\3\34\36\32\15\34\2\32\12\34\54\32\16\34\14\0\44\32\24\34"+
    "\10\0\12\34\3\0\3\32\12\34\44\32\2\0\11\32\107\0\3\34"+
    "\1\0\25\34\4\32\1\34\4\32\3\34\2\32\3\34\6\0\300\32"+
    "\72\34\1\0\5\34\u0116\32\2\0\6\32\2\0\46\32\2\0\6\32"+
    "\2\0\10\32\1\0\1\32\1\0\1\32\1\0\1\32\1\0\37\32"+
    "\2\0\65\32\1\0\7\32\1\0\1\32\3\0\3\32\1\0\7\32"+
    "\3\0\4\32\2\0\6\32\4\0\15\32\5\0\3\32\1\0\7\32"+
    "\16\0\5\34\32\0\5\34\20\0\2\32\23\0\1\32\13\0\5\34"+
    "\1\0\12\34\1\0\1\32\15\0\1\32\20\0\15\32\3\0\40\32"+
    "\20\0\15\34\4\0\1\34\3\0\14\34\21\0\1\32\4\0\1\32"+
    "\2\0\12\32\1\0\1\32\3\0\5\32\6\0\1\32\1\0\1\32"+
    "\1\0\1\32\1\0\4\32\1\0\13\32\2\0\4\32\5\0\5\32"+
    "\4\0\1\32\21\0\51\32\u0a77\0\57\32\1\0\57\32\1\0\205\32"+
    "\6\0\4\32\3\34\2\32\14\0\46\32\1\0\1\32\5\0\1\32"+
    "\2\0\70\32\7\0\1\32\17\0\1\34\27\32\11\0\7\32\1\0"+
    "\7\32\1\0\7\32\1\0\7\32\1\0\7\32\1\0\7\32\1\0"+
    "\7\32\1\0\7\32\1\0\40\34\57\0\1\32\u01d5\0\3\32\31\0"+
    "\11\32\6\34\1\0\5\32\2\0\5\32\4\0\126\32\2\0\2\34"+
    "\2\0\3\32\1\0\132\32\1\0\4\32\5\0\52\32\2\0\136\32"+
    "\21\0\33\32\65\0\20\32\u0200\0\u19b6\32\112\0\u51eb\32\25\0\u048d\32"+
    "\103\0\56\32\2\0\u010d\32\3\0\20\32\12\34\2\32\24\0\57\32"+
    "\1\34\4\0\12\34\1\0\37\32\2\34\120\32\2\34\45\0\11\32"+
    "\2\0\147\32\2\0\44\32\1\0\10\32\77\0\13\32\1\34\3\32"+
    "\1\34\4\32\1\34\27\32\5\34\20\0\1\32\7\0\64\32\14\0"+
    "\2\34\62\32\22\34\12\0\12\34\6\0\22\34\6\32\3\0\1\32"+
    "\1\0\1\32\2\0\12\34\34\32\10\34\2\0\27\32\15\34\14\0"+
    "\35\32\3\0\4\34\57\32\16\34\16\0\1\32\12\34\6\0\5\32"+
    "\1\34\12\32\12\34\5\32\1\0\51\32\16\34\11\0\3\32\1\34"+
    "\10\32\2\34\2\0\12\34\6\0\27\32\3\0\1\32\3\34\62\32"+
    "\1\34\1\32\3\34\2\32\2\34\5\32\2\34\1\32\1\34\1\32"+
    "\30\0\3\32\2\0\13\32\5\34\2\0\3\32\2\34\12\0\6\32"+
    "\2\0\6\32\2\0\6\32\11\0\7\32\1\0\7\32\1\0\53\32"+
    "\1\0\12\32\12\0\163\32\10\34\1\0\2\34\2\0\12\34\6\0"+
    "\u2ba4\32\14\0\27\32\4\0\61\32\u2104\0\u016e\32\2\0\152\32\46\0"+
    "\7\32\14\0\5\32\5\0\1\32\1\34\12\32\1\0\15\32\1\0"+
    "\5\32\1\0\1\32\1\0\2\32\1\0\2\32\1\0\154\32\41\0"+
    "\u016b\32\22\0\100\32\2\0\66\32\50\0\15\32\3\0\20\34\20\0"+
    "\20\34\3\0\2\32\30\0\3\32\31\0\1\32\6\0\5\32\1\0"+
    "\207\32\2\0\1\34\4\0\1\32\13\0\12\34\7\0\32\32\4\0"+
    "\1\32\1\0\32\32\13\0\131\32\3\0\6\32\2\0\6\32\2\0"+
    "\6\32\2\0\3\32\3\0\2\32\3\0\2\32\22\0\3\34\4\0"+
    "\14\32\1\0\32\32\1\0\23\32\1\0\2\32\1\0\17\32\2\0"+
    "\16\32\42\0\173\32\105\0\65\32\210\0\1\34\202\0\35\32\3\0"+
    "\61\32\17\0\1\34\37\0\40\32\15\0\36\32\5\0\46\32\5\34"+
    "\5\0\36\32\2\0\44\32\4\0\10\32\1\0\5\32\52\0\236\32"+
    "\2\0\12\34\6\0\44\32\4\0\44\32\4\0\50\32\10\0\64\32"+
    "\234\0\u0137\32\11\0\26\32\12\0\10\32\230\0\6\32\2\0\1\32"+
    "\1\0\54\32\1\0\2\32\3\0\1\32\2\0\27\32\12\0\27\32"+
    "\11\0\37\32\101\0\23\32\1\0\2\32\12\0\26\32\12\0\32\32"+
    "\106\0\70\32\6\0\2\32\100\0\1\32\3\34\1\0\2\34\5\0"+
    "\4\34\4\32\1\0\3\32\1\0\33\32\4\0\3\34\4\0\1\34"+
    "\40\0\35\32\3\0\35\32\43\0\10\32\1\0\34\32\2\34\31\0"+
    "\66\32\12\0\26\32\12\0\23\32\15\0\22\32\156\0\111\32\67\0"+
    "\63\32\15\0\63\32\u030d\0\3\34\65\32\17\34\37\0\12\34\17\0"+
    "\4\34\55\32\13\34\2\0\1\34\22\0\31\32\7\0\12\34\6\0"+
    "\3\34\44\32\16\34\1\0\12\34\20\0\43\32\1\34\2\0\1\32"+
    "\11\0\3\34\60\32\16\34\4\32\5\0\3\34\3\0\12\34\1\32"+
    "\1\0\1\32\43\0\22\32\1\0\31\32\14\34\6\0\1\34\101\0"+
    "\7\32\1\0\1\32\1\0\4\32\1\0\17\32\1\0\12\32\7\0"+
    "\57\32\14\34\5\0\12\34\6\0\4\34\1\0\10\32\2\0\2\32"+
    "\2\0\26\32\1\0\7\32\1\0\2\32\1\0\5\32\2\0\1\34"+
    "\1\32\7\34\2\0\2\34\2\0\3\34\2\0\1\32\6\0\1\34"+
    "\5\0\5\32\2\34\2\0\7\34\3\0\5\34\213\0\65\32\22\34"+
    "\4\32\5\0\12\34\46\0\60\32\24\34\2\32\1\0\1\32\10\0"+
    "\12\34\246\0\57\32\7\34\2\0\11\34\27\0\4\32\2\34\42\0"+
    "\60\32\21\34\3\0\1\32\13\0\12\34\46\0\53\32\15\34\10\0"+
    "\12\34\66\0\32\32\3\0\17\34\4\0\12\34\u0166\0\100\32\12\34"+
    "\25\0\1\32\u0100\0\1\32\12\34\50\32\7\34\1\32\4\34\10\0"+
    "\1\34\10\0\1\32\13\34\50\32\2\0\4\32\20\34\46\0\71\32"+
    "\u0107\0\11\32\1\0\45\32\10\34\1\0\10\34\1\32\17\0\12\34"+
    "\30\0\36\32\2\0\26\34\1\0\16\34\111\0\7\32\1\0\2\32"+
    "\1\0\46\32\6\34\3\0\1\34\1\0\2\34\1\0\7\34\1\32"+
    "\1\34\10\0\12\34\u02a6\0\u039a\32\146\0\157\32\21\0\304\32\u0abc\0"+
    "\u042f\32\u0fd1\0\u0247\32\u21b9\0\u0239\32\7\0\37\32\1\0\12\34\146\0"+
    "\36\32\2\0\5\34\13\0\60\32\7\34\11\0\4\32\14\0\12\34"+
    "\11\0\25\32\5\0\23\32\u0370\0\105\32\13\0\1\32\56\34\20\0"+
    "\4\34\15\32\100\0\2\32\36\0\u17ed\32\23\0\u02f3\32\u250d\0\u011f\32"+
    "\121\0\u018c\32\u0904\0\153\32\5\0\15\32\3\0\11\32\7\0\12\32"+
    "\3\0\2\34\1\0\4\34\u14c1\0\5\34\3\0\26\34\2\0\7\34"+
    "\36\0\4\34\224\0\3\34\u01bb\0\125\32\1\0\107\32\1\0\2\32"+
    "\2\0\1\32\2\0\2\32\2\0\4\32\1\0\14\32\1\0\1\32"+
    "\1\0\7\32\1\0\101\32\1\0\4\32\2\0\10\32\1\0\7\32"+
    "\1\0\34\32\1\0\4\32\1\0\5\32\1\0\1\32\3\0\7\32"+
    "\1\0\u0154\32\2\0\31\32\1\0\31\32\1\0\37\32\1\0\31\32"+
    "\1\0\37\32\1\0\31\32\1\0\37\32\1\0\31\32\1\0\37\32"+
    "\1\0\31\32\1\0\10\32\2\0\62\34\u0200\0\67\34\4\0\62\34"+
    "\10\0\1\34\16\0\1\34\26\0\5\34\1\0\17\34\u0550\0\7\34"+
    "\1\0\21\34\2\0\7\34\1\0\2\34\1\0\5\34\u07d5\0\305\32"+
    "\13\0\7\34\51\0\104\32\7\34\5\0\12\34\u04a6\0\4\32\1\0"+
    "\33\32\1\0\2\32\1\0\1\32\2\0\1\32\1\0\12\32\1\0"+
    "\4\32\1\0\1\32\1\0\1\32\6\0\1\32\4\0\1\32\1\0"+
    "\1\32\1\0\1\32\1\0\3\32\1\0\2\32\1\0\1\32\2\0"+
    "\1\32\1\0\1\32\1\0\1\32\1\0\1\32\1\0\1\32\1\0"+
    "\2\32\1\0\1\32\2\0\4\32\1\0\7\32\1\0\4\32\1\0"+
    "\4\32\1\0\1\32\1\0\12\32\1\0\21\32\5\0\3\32\1\0"+
    "\5\32\1\0\21\32\u1144\0\ua6d7\32\51\0\u1035\32\13\0\336\32\2\0"+
    "\u1682\32\16\0\u1d31\32\u0c1f\0\u021e\32\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\34\36\0\140\34\200\0\360\34\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\1\2\6"+
    "\4\7\1\10\1\1\1\11\1\12\2\1\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\11\7\1\1"+
    "\2\0\1\23\1\24\3\7\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\10\7\1\33\1\7\1\0\1\34\2\0"+
    "\5\7\1\35\6\7\3\0\1\36\1\37\5\7\1\40"+
    "\3\7\3\0\4\7\1\41\1\42\2\7\1\0\1\43"+
    "\1\0\2\7\1\44\3\7\1\43\1\0\1\45\4\7"+
    "\3\0\2\7\3\0\2\7\3\0\2\7\25\0\1\46"+
    "\1\47\11\0\1\50\1\51\15\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\162\0\344\0\162\0\162"+
    "\0\u011d\0\u0156\0\u018f\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac"+
    "\0\u02e5\0\u031e\0\u0357\0\u0390\0\u03c9\0\162\0\162\0\162"+
    "\0\162\0\162\0\162\0\162\0\162\0\u0402\0\u043b\0\u0474"+
    "\0\u04ad\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c"+
    "\0\u0675\0\162\0\u06ae\0\u06e7\0\u0720\0\u0759\0\162\0\162"+
    "\0\162\0\162\0\162\0\162\0\u0792\0\u07cb\0\u0804\0\u083d"+
    "\0\u0876\0\u08af\0\u08e8\0\u0921\0\u0201\0\u095a\0\u0603\0\162"+
    "\0\u0993\0\u09cc\0\u0a05\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0201"+
    "\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1"+
    "\0\u0cea\0\u0201\0\u0201\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\u0e07"+
    "\0\u0201\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96"+
    "\0\u0fcf\0\u1008\0\u1041\0\u0201\0\u0201\0\u107a\0\u10b3\0\u10ec"+
    "\0\u0c78\0\u1125\0\u115e\0\u1197\0\u0201\0\u11d0\0\u1209\0\u1242"+
    "\0\162\0\u127b\0\u0201\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398"+
    "\0\u13d1\0\u140a\0\u1443\0\u147c\0\u14b5\0\u14ee\0\u1527\0\u1560"+
    "\0\u1599\0\u15d2\0\u160b\0\u1644\0\u167d\0\u16b6\0\u16ef\0\u1728"+
    "\0\u1761\0\u179a\0\u17d3\0\u180c\0\u1845\0\u187e\0\u18b7\0\u18f0"+
    "\0\u1929\0\u1962\0\u199b\0\u19d4\0\u1a0d\0\u1a46\0\u1a7f\0\u1ab8"+
    "\0\u1af1\0\u1b2a\0\u1b63\0\162\0\162\0\u1b9c\0\u1bd5\0\u1c0e"+
    "\0\u1c47\0\u1c80\0\u1cb9\0\u1cf2\0\u1d2b\0\u1d64\0\162\0\162"+
    "\0\u1d9d\0\u1dd6\0\u1e0f\0\u1e48\0\u1e81\0\u1eba\0\u1ef3\0\u1f2c"+
    "\0\u1f65\0\u1f9e\0\u1fd7\0\u2010\0\u2049";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\3"+
    "\1\12\1\13\1\3\1\14\2\15\1\16\1\17\3\15"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\2\15\1\3"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\7\15\1\42\1\15\1\43"+
    "\1\44\1\15\1\45\1\46\2\15\14\3\10\47\6\3"+
    "\2\47\11\3\24\47\73\0\1\5\72\0\1\50\67\0"+
    "\1\51\3\0\1\52\14\51\1\0\1\51\5\0\1\51"+
    "\11\0\24\51\11\0\2\12\1\53\70\0\1\53\66\0"+
    "\2\15\1\0\1\15\1\54\6\15\6\0\3\15\10\0"+
    "\24\15\11\0\2\15\1\0\10\15\6\0\3\15\10\0"+
    "\24\15\11\0\2\15\1\0\6\15\1\55\1\15\6\0"+
    "\3\15\10\0\24\15\11\0\2\15\1\0\5\15\1\56"+
    "\2\15\6\0\3\15\10\0\24\15\24\0\1\57\70\0"+
    "\1\60\70\0\1\61\70\0\1\62\74\0\1\63\71\0"+
    "\1\64\50\0\2\15\1\0\10\15\6\0\3\15\10\0"+
    "\1\15\1\65\17\15\1\66\2\15\11\0\2\15\1\0"+
    "\10\15\6\0\3\15\10\0\11\15\1\67\12\15\11\0"+
    "\2\15\1\0\10\15\6\0\3\15\10\0\7\15\1\70"+
    "\14\15\11\0\2\15\1\0\10\15\6\0\3\15\10\0"+
    "\10\15\1\71\13\15\11\0\2\15\1\0\10\15\6\0"+
    "\3\15\10\0\4\15\1\72\17\15\11\0\2\15\1\0"+
    "\10\15\6\0\3\15\10\0\14\15\1\73\7\15\11\0"+
    "\2\15\1\0\10\15\6\0\3\15\10\0\17\15\1\74"+
    "\4\15\11\0\2\15\1\0\4\15\1\75\3\15\6\0"+
    "\3\15\10\0\24\15\11\0\2\15\1\0\10\15\6\0"+
    "\3\15\10\0\11\15\1\76\12\15\11\0\2\77\1\0"+
    "\10\77\6\0\3\77\1\100\7\0\24\77\5\0\1\101"+
    "\66\0\1\102\3\0\1\52\14\102\1\0\1\102\5\0"+
    "\1\102\11\0\24\102\11\0\2\53\67\0\2\15\1\0"+
    "\2\15\1\103\5\15\6\0\3\15\10\0\24\15\11\0"+
    "\2\15\1\0\7\15\1\104\6\0\3\15\10\0\24\15"+
    "\11\0\2\15\1\0\6\15\1\105\1\15\6\0\3\15"+
    "\10\0\24\15\11\0\2\15\1\0\10\15\6\0\3\15"+
    "\10\0\2\15\1\106\21\15\11\0\2\15\1\0\10\15"+
    "\6\0\3\15\10\0\22\15\1\107\1\15\11\0\2\15"+
    "\1\0\10\15\6\0\3\15\10\0\7\15\1\110\14\15"+
    "\11\0\2\15\1\0\10\15\6\0\3\15\10\0\10\15"+
    "\1\111\13\15\11\0\2\15\1\0\10\15\6\0\3\15"+
    "\10\0\14\15\1\112\7\15\11\0\2\15\1\0\10\15"+
    "\6\0\3\15\10\0\14\15\1\113\7\15\11\0\2\15"+
    "\1\0\10\15\6\0\3\15\10\0\14\15\1\114\7\15"+
    "\11\0\2\15\1\0\10\15\6\0\3\15\10\0\20\15"+
    "\1\115\3\15\11\0\2\15\1\0\10\15\6\0\3\15"+
    "\10\0\1\116\23\15\5\117\1\120\1\0\62\117\3\0"+
    "\1\121\3\0\1\52\14\121\1\0\1\121\5\0\1\121"+
    "\11\0\24\121\11\0\2\15\1\0\3\15\1\122\4\15"+
    "\6\0\3\15\10\0\24\15\11\0\2\15\1\0\3\15"+
    "\1\123\4\15\6\0\3\15\10\0\24\15\11\0\2\15"+
    "\1\0\7\15\1\103\6\0\3\15\10\0\24\15\11\0"+
    "\2\15\1\0\10\15\6\0\3\15\10\0\3\15\1\124"+
    "\20\15\11\0\2\15\1\0\10\15\6\0\3\15\10\0"+
    "\4\15\1\125\17\15\11\0\2\15\1\0\10\15\6\0"+
    "\3\15\10\0\1\15\1\126\22\15\11\0\2\15\1\0"+
    "\10\15\6\0\3\15\10\0\12\15\1\127\11\15\11\0"+
    "\2\15\1\0\10\15\6\0\3\15\10\0\5\15\1\130"+
    "\16\15\11\0\2\15\1\0\10\15\6\0\3\15\10\0"+
    "\4\15\1\131\17\15\11\0\2\15\1\0\6\15\1\132"+
    "\1\15\6\0\3\15\10\0\24\15\11\0\2\15\1\0"+
    "\10\15\6\0\3\15\10\0\1\133\2\15\1\134\20\15"+
    "\5\117\1\135\67\117\1\136\1\135\63\117\3\0\1\137"+
    "\3\0\1\52\14\137\1\0\1\137\5\0\1\137\11\0"+
    "\24\137\11\0\2\15\1\0\10\15\6\0\3\15\10\0"+
    "\4\15\1\140\17\15\11\0\2\15\1\0\10\15\6\0"+
    "\3\15\10\0\5\15\1\141\16\15\11\0\2\15\1\0"+
    "\10\15\6\0\3\15\10\0\11\15\1\142\12\15\11\0"+
    "\2\15\1\0\10\15\6\0\3\15\10\0\10\15\1\143"+
    "\13\15\11\0\2\15\1\0\10\15\6\0\3\15\10\0"+
    "\7\15\1\144\14\15\11\0\2\15\1\0\3\15\1\145"+
    "\4\15\6\0\3\15\10\0\24\15\11\0\2\15\1\0"+
    "\10\15\6\0\3\15\10\0\21\15\1\146\2\15\11\0"+
    "\2\15\1\0\10\15\6\0\3\15\10\0\10\15\1\147"+
    "\13\15\4\117\1\150\1\135\67\117\1\151\1\135\63\117"+
    "\3\0\1\152\3\0\1\52\14\152\1\0\1\152\5\0"+
    "\1\152\11\0\24\152\11\0\2\15\1\0\10\15\6\0"+
    "\3\15\10\0\5\15\1\153\16\15\11\0\2\15\1\0"+
    "\10\15\6\0\3\15\10\0\10\15\1\154\13\15\11\0"+
    "\2\15\1\0\10\15\6\0\3\15\10\0\12\15\1\155"+
    "\11\15\11\0\2\15\1\0\10\15\6\0\3\15\10\0"+
    "\5\15\1\156\16\15\11\0\2\15\1\0\10\15\6\0"+
    "\3\15\10\0\22\15\1\157\1\15\11\0\2\15\1\0"+
    "\10\15\6\0\3\15\10\0\14\15\1\160\7\15\4\117"+
    "\1\161\1\135\63\117\3\0\1\162\3\0\1\52\14\162"+
    "\1\0\1\162\5\0\1\162\11\0\24\162\11\0\2\15"+
    "\1\0\10\15\6\0\3\15\10\0\6\15\1\163\15\15"+
    "\11\0\2\15\1\0\10\15\6\0\3\15\10\0\21\15"+
    "\1\164\2\15\11\0\2\15\1\0\10\15\6\0\3\15"+
    "\10\0\23\15\1\165\11\0\2\15\1\0\10\15\6\0"+
    "\3\15\10\0\4\15\1\166\17\15\11\0\2\15\1\0"+
    "\10\15\6\0\3\15\10\0\12\15\1\167\11\15\3\0"+
    "\1\170\3\0\1\52\14\170\1\0\1\170\5\0\1\170"+
    "\11\0\24\170\11\0\2\15\1\171\10\15\6\0\3\15"+
    "\10\0\24\15\11\0\2\15\1\172\10\15\6\0\3\15"+
    "\10\0\24\15\11\0\2\15\1\0\10\15\6\0\3\15"+
    "\10\0\5\15\1\173\16\15\11\0\2\15\1\0\10\15"+
    "\6\0\3\15\10\0\10\15\1\174\13\15\3\0\1\175"+
    "\3\0\1\52\14\175\1\0\1\175\5\0\1\175\11\0"+
    "\24\175\47\0\1\176\70\0\1\177\32\0\2\15\1\0"+
    "\10\15\6\0\3\15\10\0\10\15\1\200\13\15\11\0"+
    "\2\15\1\0\10\15\6\0\3\15\10\0\5\15\1\201"+
    "\16\15\3\0\1\202\3\0\1\52\14\202\1\0\1\202"+
    "\5\0\1\202\11\0\24\202\66\0\1\203\70\0\1\204"+
    "\13\0\2\15\1\0\10\15\6\0\3\15\10\0\21\15"+
    "\1\205\2\15\11\0\2\15\1\0\10\15\6\0\3\15"+
    "\10\0\23\15\1\206\3\0\1\207\3\0\1\52\14\207"+
    "\1\0\1\207\5\0\1\207\11\0\24\207\67\0\1\210"+
    "\70\0\1\211\12\0\2\15\1\212\10\15\6\0\3\15"+
    "\10\0\24\15\11\0\2\15\1\213\10\15\6\0\3\15"+
    "\10\0\24\15\3\0\1\214\3\0\1\52\14\214\1\0"+
    "\1\214\5\0\1\214\11\0\24\214\54\0\1\215\70\0"+
    "\1\216\63\0\1\217\70\0\1\220\24\0\1\221\3\0"+
    "\1\52\14\221\1\0\1\221\5\0\1\221\11\0\24\221"+
    "\46\0\1\222\70\0\1\223\110\0\1\224\70\0\1\225"+
    "\5\0\1\226\3\0\1\52\14\226\1\0\1\226\5\0"+
    "\1\226\11\0\24\226\61\0\1\227\70\0\1\230\76\0"+
    "\1\231\70\0\1\232\4\0\1\233\3\0\1\52\14\233"+
    "\1\0\1\233\5\0\1\233\11\0\24\233\56\0\1\234"+
    "\70\0\1\235\66\0\1\236\70\0\1\237\17\0\1\240"+
    "\3\0\1\52\14\240\1\0\1\240\5\0\1\240\11\0"+
    "\24\240\46\0\1\241\70\0\1\242\25\0\1\243\3\0"+
    "\1\52\14\243\1\0\1\243\5\0\1\243\11\0\24\243"+
    "\61\0\1\244\70\0\1\245\12\0\1\246\3\0\1\52"+
    "\14\246\1\0\1\246\5\0\1\246\11\0\24\246\56\0"+
    "\1\247\70\0\1\250\15\0\1\251\3\0\1\52\14\251"+
    "\1\0\1\251\5\0\1\251\11\0\24\251\3\0\1\252"+
    "\3\0\1\52\14\252\1\0\1\252\5\0\1\252\11\0"+
    "\24\252\3\0\1\253\3\0\1\52\14\253\1\0\1\253"+
    "\5\0\1\253\11\0\24\253\3\0\1\254\3\0\1\52"+
    "\14\254\1\0\1\254\5\0\1\254\11\0\24\254\3\0"+
    "\1\255\3\0\1\52\14\255\1\0\1\255\5\0\1\255"+
    "\11\0\24\255\3\0\1\256\3\0\1\52\14\256\1\0"+
    "\1\256\5\0\1\256\11\0\24\256\3\0\1\257\3\0"+
    "\1\52\14\257\1\0\1\257\5\0\1\257\11\0\24\257"+
    "\3\0\1\260\3\0\1\52\14\260\1\0\1\260\5\0"+
    "\1\260\11\0\24\260\3\0\1\261\3\0\1\52\14\261"+
    "\1\0\1\261\5\0\1\261\11\0\24\261\3\0\1\262"+
    "\3\0\1\52\14\262\1\0\1\262\5\0\1\262\11\0"+
    "\24\262\3\0\1\263\3\0\1\52\14\263\1\0\1\263"+
    "\5\0\1\263\11\0\24\263\3\0\1\264\3\0\1\52"+
    "\14\264\1\0\1\264\5\0\1\264\11\0\24\264\3\0"+
    "\1\265\3\0\1\52\14\265\1\0\1\265\5\0\1\265"+
    "\11\0\24\265\7\0\1\52\61\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8322];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\1\1\2\11\15\1\10\11"+
    "\12\1\2\0\1\11\4\1\6\11\12\1\1\0\1\11"+
    "\2\0\14\1\3\0\13\1\3\0\10\1\1\0\1\1"+
    "\1\0\6\1\1\11\1\0\5\1\3\0\2\1\3\0"+
    "\2\1\3\0\2\1\25\0\2\11\11\0\2\11\15\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  BufferedWriter  bw;
  File file;
  ArrayList<String> simbolos;

  public void writeTable(String str) throws IOException{
    if (!simbolos.contains(str.split(",")[0])) {
      bw.write(str);
      bw.newLine();
      bw.flush();
      simbolos.add(str.split(",")[0]);
    }
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    try {
    file = new File("../ts.txt");
    bw = new BufferedWriter(new FileWriter(file, true));
    simbolos = new ArrayList<>();
  } catch (IOException e) {
    e.printStackTrace();
  }
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3490) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Caracter no permitido: <" + yytext() + "> en la linea " + yyline);
            } 
            // fall through
          case 42: break;
          case 2: 
            { /* Así ignora los espacios en blanco */
            } 
            // fall through
          case 43: break;
          case 3: 
            { System.out.printf("\n>>> Simbolo Resta: [%s] encontrado en linea %d, columna %d\n",yytext() , yyline, yycolumn);return new Symbol(sym.RESTA, yychar, yyline);
            } 
            // fall through
          case 44: break;
          case 4: 
            { System.out.printf("\n>>> Simbolo Division: [%s] encontrado en linea %d, columna %d\n",yytext() , yyline, yycolumn);return new Symbol(sym.DIVISION, yychar, yyline);
            } 
            // fall through
          case 45: break;
          case 5: 
            { System.out.printf("\n>>> Simbolo Multiplicacion: [%s] encontrado en linea %d, columna %d\n",yytext() , yyline, yycolumn);return new Symbol(sym.MULTIPLICAION, yychar, yyline);
            } 
            // fall through
          case 46: break;
          case 6: 
            { if ((Integer.valueOf(yytext()) > -32768) && (Integer.valueOf(yytext()) < 32768)) {
                                    System.out.printf("\n>>> Integer encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
                                    writeTable("_"+yytext()+",CTE_INT,,"+yytext()+",");
                                    return new Symbol(sym.CONST_INTEGER, yychar, yyline, new String(yytext()));
                                  }
            } 
            // fall through
          case 47: break;
          case 7: 
            { System.out.printf("\n>>> Identificador encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
                                  return new Symbol(sym.ID, yychar, yyline, new String(yytext()));
            } 
            // fall through
          case 48: break;
          case 8: 
            { System.out.printf("\n>>> Simbolo Asignacion encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.ASIGNACION, yychar, yyline);
            } 
            // fall through
          case 49: break;
          case 9: 
            { System.out.printf("\n>>> Simbolo Mayor encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.MAYOR, yychar, yyline);
            } 
            // fall through
          case 50: break;
          case 10: 
            { System.out.printf("\n>>> Simbolo Menor encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.MENOR, yychar, yyline);
            } 
            // fall through
          case 51: break;
          case 11: 
            { System.out.printf("\n>>> Simbolo Punto y Coma encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.PUNTO_Y_COMA, yychar, yyline);
            } 
            // fall through
          case 52: break;
          case 12: 
            { System.out.printf("\n>>> Simbolo Dos Puntos encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.DOS_PUNTOS, yychar, yyline);
            } 
            // fall through
          case 53: break;
          case 13: 
            { System.out.printf("\n>>> Simbolo coma encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.COMA, yychar, yyline);
            } 
            // fall through
          case 54: break;
          case 14: 
            { System.out.printf("\n>>> Simbolo Parentesis Abre encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.PARENTESIS_ABRE, yychar, yyline);
            } 
            // fall through
          case 55: break;
          case 15: 
            { System.out.printf("\n>>> Simbolo Parentesis Cierra encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.PARENTESIS_CIERRA, yychar, yyline);
            } 
            // fall through
          case 56: break;
          case 16: 
            { System.out.printf("\n>>> Simbolo Llaves Abre encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.LLAVES_ABRE, yychar, yyline);
            } 
            // fall through
          case 57: break;
          case 17: 
            { System.out.printf("\n>>> Simbolo Llaves Cierra encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.LLAVES_CIERRA, yychar, yyline);
            } 
            // fall through
          case 58: break;
          case 18: 
            { System.out.printf("\n>>> Simbolo Suma: [%s] encontrado en linea %d, columna %d\n",yytext() , yyline, yycolumn);return new Symbol(sym.SUMA, yychar, yyline);
            } 
            // fall through
          case 59: break;
          case 19: 
            { System.out.printf("\n>>> String encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
                                  writeTable("_"+yytext()+",CTE_STR,,"+yytext()+","+yytext().length());
                                  return new Symbol(sym.CONST_STRING, yychar, yyline, new String(yytext()));
            } 
            // fall through
          case 60: break;
          case 20: 
            { /* real de 32 bits : 16 parte entera y 16 parte decimal*/
									                int indexDecimal = yytext().indexOf(".");
								                  String entero = yytext().substring(0, indexDecimal);
								                  String decimal = yytext().substring(indexDecimal+1,yytext().length());

                								  if ( (Integer.valueOf(entero) > -32768) && (Integer.valueOf(entero) < 32768)
                								       && (Integer.valueOf(decimal) > -32768) && (Integer.valueOf(decimal) < 32768) ) {
                                          System.out.printf("\n>>> Float encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
                                          writeTable("_"+yytext()+",CTE_FLOAT,,"+yytext()+",");
                                          return new Symbol(sym.CONST_FLOAT, yychar, yyline, new String(yytext()));
                                  }
            } 
            // fall through
          case 61: break;
          case 21: 
            { System.out.printf("\n>>> Simbolo Igual encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.IGUAL, yychar, yyline);
            } 
            // fall through
          case 62: break;
          case 22: 
            { System.out.printf("\n>>> Simbolo Distinto encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.DISTINTO, yychar, yyline);
            } 
            // fall through
          case 63: break;
          case 23: 
            { System.out.printf("\n>>> Simbolo MenorIgual  encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.MENOR_IGUAL, yychar, yyline);
            } 
            // fall through
          case 64: break;
          case 24: 
            { System.out.printf("\n>>> Simbolo MayorIgual encontrado en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.MAYOR_IGUAL, yychar, yyline);
            } 
            // fall through
          case 65: break;
          case 25: 
            { System.out.printf("\n>>> Simbolo AND: [%s] encontrado en linea %d, columna %d\n",yytext(), yyline, yycolumn); return new Symbol(sym.AND, yychar, yyline);
            } 
            // fall through
          case 66: break;
          case 26: 
            { System.out.printf("\n>>> Simbolo OR: [%s] encontrado en linea %d, columna %d\n",yytext() , yyline, yycolumn); return new Symbol(sym.OR, yychar, yyline);
            } 
            // fall through
          case 67: break;
          case 27: 
            { System.out.printf("\n>>> if en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.IF, yychar, yyline);
            } 
            // fall through
          case 68: break;
          case 28: 
            { System.out.printf("\n>>> DISPLAY encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);yybegin(YYINITIAL);
            } 
            // fall through
          case 69: break;
          case 29: 
            { System.out.printf("\n>>> Funcion encontrada en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.TYPE_INTEGER, yychar, yyline);
            } 
            // fall through
          case 70: break;
          case 30: 
            { System.out.printf("\n>>> Bool encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
                                  writeTable("_"+yytext()+",CTE_BOOL,,"+yytext()+",");
                                  return new Symbol(sym.CONST_BOOL, yychar, yyline, new String(yytext()));
            } 
            // fall through
          case 71: break;
          case 31: 
            { System.out.printf("\n>>> else en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.ELSE, yychar, yyline);
            } 
            // fall through
          case 72: break;
          case 32: 
            { System.out.printf("\n>>> Funcion encontrada en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.TYPE_BOOL, yychar, yyline);
            } 
            // fall through
          case 73: break;
          case 33: 
            { System.out.printf("\n>>> Funcion encontrada en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.TYPE_FLOAT, yychar, yyline);
            } 
            // fall through
          case 74: break;
          case 34: 
            { System.out.printf("\n>>> while en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.WHILE, yychar, yyline);
            } 
            // fall through
          case 75: break;
          case 35: 
            { /* Así ignora los comentarios */
            } 
            // fall through
          case 76: break;
          case 36: 
            { System.out.printf("\n>>> Funcion consta en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.TYPE_STRING, yychar, yyline);
            } 
            // fall through
          case 77: break;
          case 37: 
            { System.out.printf("\n>>> Funcion encontrada en linea %d, columna %d\n", yyline, yycolumn);yybegin(DISPLAY);return new Symbol(sym.DISPLAY_FUNCTION, yychar, yyline);
            } 
            // fall through
          case 78: break;
          case 38: 
            { System.out.printf("\n>>> DECLARE en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.DECLARE_SECTION, yychar, yyline);
            } 
            // fall through
          case 79: break;
          case 39: 
            { System.out.printf("\n>>> PROGRAM en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.PROGRAM_SECTION, yychar, yyline);
            } 
            // fall through
          case 80: break;
          case 40: 
            { System.out.printf("\n>>> ENDDECLARE en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.ENDDECLARE_SECTION, yychar, yyline);
            } 
            // fall through
          case 81: break;
          case 41: 
            { System.out.printf("\n>>> ENDPROGRAM en linea %d, columna %d\n", yyline, yycolumn); return new Symbol(sym.ENDPROGRAM_SECTION, yychar, yyline);
            } 
            // fall through
          case 82: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
