/* The following code was generated by JFlex 1.7.0 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/Users/mr.grassho/Documents/Teoria1/teoria1/my-app/src/main/jflex/Lexico1.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\25\1\3\1\2\1\0\1\3\1\1\16\25\4\0\1\3\1\22"+
    "\1\4\1\0\1\24\1\0\1\0\3\0\1\7\1\0\2\0\1\10"+
    "\1\0\1\6\11\6\1\0\1\26\1\23\1\21\1\23\2\0\32\5"+
    "\4\0\1\24\1\0\1\16\3\5\1\14\1\15\5\5\1\17\5\5"+
    "\1\12\1\20\1\11\1\13\5\5\1\0\1\7\2\0\41\25\2\0"+
    "\4\24\4\0\1\24\2\0\1\25\7\0\1\24\4\0\1\24\5\0"+
    "\27\24\1\0\37\24\1\0\u01ca\24\4\0\14\24\16\0\5\24\7\0"+
    "\1\24\1\0\1\24\21\0\160\25\5\24\1\0\2\24\2\0\4\24"+
    "\10\0\1\24\1\0\3\24\1\0\1\24\1\0\24\24\1\0\123\24"+
    "\1\0\213\24\1\0\5\25\2\0\236\24\11\0\46\24\2\0\1\24"+
    "\7\0\47\24\7\0\1\24\1\0\55\25\1\0\1\25\1\0\2\25"+
    "\1\0\2\25\1\0\1\25\10\0\33\24\5\0\3\24\15\0\5\25"+
    "\6\0\1\24\4\0\13\25\5\0\53\24\37\25\4\0\2\24\1\25"+
    "\143\24\1\0\1\24\10\25\1\0\6\25\2\24\2\25\1\0\4\25"+
    "\2\24\12\25\3\24\2\0\1\24\17\0\1\25\1\24\1\25\36\24"+
    "\33\25\2\0\131\24\13\25\1\24\16\0\12\25\41\24\11\25\2\24"+
    "\4\0\1\24\5\0\26\24\4\25\1\24\11\25\1\24\3\25\1\24"+
    "\5\25\22\0\31\24\3\25\104\0\1\24\1\0\13\24\67\0\33\25"+
    "\1\0\4\25\66\24\3\25\1\24\22\25\1\24\7\25\12\24\2\25"+
    "\2\0\12\25\1\0\7\24\1\0\7\24\1\0\3\25\1\0\10\24"+
    "\2\0\2\24\2\0\26\24\1\0\7\24\1\0\1\24\3\0\4\24"+
    "\2\0\1\25\1\24\7\25\2\0\2\25\2\0\3\25\1\24\10\0"+
    "\1\25\4\0\2\24\1\0\3\24\2\25\2\0\12\25\4\24\7\0"+
    "\1\24\5\0\3\25\1\0\6\24\4\0\2\24\2\0\26\24\1\0"+
    "\7\24\1\0\2\24\1\0\2\24\1\0\2\24\2\0\1\25\1\0"+
    "\5\25\4\0\2\25\2\0\3\25\3\0\1\25\7\0\4\24\1\0"+
    "\1\24\7\0\14\25\3\24\1\25\13\0\3\25\1\0\11\24\1\0"+
    "\3\24\1\0\26\24\1\0\7\24\1\0\2\24\1\0\5\24\2\0"+
    "\1\25\1\24\10\25\1\0\3\25\1\0\3\25\2\0\1\24\17\0"+
    "\2\24\2\25\2\0\12\25\1\0\1\24\17\0\3\25\1\0\10\24"+
    "\2\0\2\24\2\0\26\24\1\0\7\24\1\0\2\24\1\0\5\24"+
    "\2\0\1\25\1\24\7\25\2\0\2\25\2\0\3\25\10\0\2\25"+
    "\4\0\2\24\1\0\3\24\2\25\2\0\12\25\1\0\1\24\20\0"+
    "\1\25\1\24\1\0\6\24\3\0\3\24\1\0\4\24\3\0\2\24"+
    "\1\0\1\24\1\0\2\24\3\0\2\24\3\0\3\24\3\0\14\24"+
    "\4\0\5\25\3\0\3\25\1\0\4\25\2\0\1\24\6\0\1\25"+
    "\16\0\12\25\11\0\1\24\7\0\3\25\1\0\10\24\1\0\3\24"+
    "\1\0\27\24\1\0\12\24\1\0\5\24\3\0\1\24\7\25\1\0"+
    "\3\25\1\0\4\25\7\0\2\25\1\0\2\24\6\0\2\24\2\25"+
    "\2\0\12\25\22\0\2\25\1\0\10\24\1\0\3\24\1\0\27\24"+
    "\1\0\12\24\1\0\5\24\2\0\1\25\1\24\7\25\1\0\3\25"+
    "\1\0\4\25\7\0\2\25\7\0\1\24\1\0\2\24\2\25\2\0"+
    "\12\25\1\0\2\24\17\0\2\25\1\0\10\24\1\0\3\24\1\0"+
    "\51\24\2\0\1\24\7\25\1\0\3\25\1\0\4\25\1\24\10\0"+
    "\1\25\10\0\2\24\2\25\2\0\12\25\12\0\6\24\2\0\2\25"+
    "\1\0\22\24\3\0\30\24\1\0\11\24\1\0\1\24\2\0\7\24"+
    "\3\0\1\25\4\0\6\25\1\0\1\25\1\0\10\25\22\0\2\25"+
    "\15\0\60\24\1\25\2\24\7\25\4\0\10\24\10\25\1\0\12\25"+
    "\47\0\2\24\1\0\1\24\2\0\2\24\1\0\1\24\2\0\1\24"+
    "\6\0\4\24\1\0\7\24\1\0\3\24\1\0\1\24\1\0\1\24"+
    "\2\0\2\24\1\0\4\24\1\25\2\24\6\25\1\0\2\25\1\24"+
    "\2\0\5\24\1\0\1\24\1\0\6\25\2\0\12\25\2\0\4\24"+
    "\40\0\1\24\27\0\2\25\6\0\12\25\13\0\1\25\1\0\1\25"+
    "\1\0\1\25\4\0\2\25\10\24\1\0\44\24\4\0\24\25\1\0"+
    "\2\25\5\24\13\25\1\0\44\25\11\0\1\25\71\0\53\24\24\25"+
    "\1\24\12\25\6\0\6\24\4\25\4\24\3\25\1\24\3\25\2\24"+
    "\7\25\3\24\4\25\15\24\14\25\1\24\17\25\2\0\46\24\1\0"+
    "\1\24\5\0\1\24\2\0\53\24\1\0\u014d\24\1\0\4\24\2\0"+
    "\7\24\1\0\1\24\1\0\4\24\2\0\51\24\1\0\4\24\2\0"+
    "\41\24\1\0\4\24\2\0\7\24\1\0\1\24\1\0\4\24\2\0"+
    "\17\24\1\0\71\24\1\0\4\24\2\0\103\24\2\0\3\25\40\0"+
    "\20\24\20\0\125\24\14\0\u026c\24\2\0\21\24\1\0\32\24\5\0"+
    "\113\24\3\0\3\24\17\0\15\24\1\0\4\24\3\25\13\0\22\24"+
    "\3\25\13\0\22\24\2\25\14\0\15\24\1\0\3\24\1\0\2\25"+
    "\14\0\64\24\40\25\3\0\1\24\3\0\2\24\1\25\2\0\12\25"+
    "\41\0\3\25\2\0\12\25\6\0\130\24\10\0\51\24\1\25\1\24"+
    "\5\0\106\24\12\0\35\24\3\0\14\25\4\0\14\25\12\0\12\25"+
    "\36\24\2\0\5\24\13\0\54\24\4\0\21\25\7\24\2\25\6\0"+
    "\12\25\46\0\27\24\5\25\4\0\65\24\12\25\1\0\35\25\2\0"+
    "\13\25\6\0\12\25\15\0\1\24\130\0\5\25\57\24\21\25\7\24"+
    "\4\0\12\25\21\0\11\25\14\0\3\25\36\24\15\25\2\24\12\25"+
    "\54\24\16\25\14\0\44\24\24\25\10\0\12\25\3\0\3\24\12\25"+
    "\44\24\122\0\3\25\1\0\25\25\4\24\1\25\4\24\3\25\2\24"+
    "\11\0\300\24\47\25\25\0\4\25\u0116\24\2\0\6\24\2\0\46\24"+
    "\2\0\6\24\2\0\10\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\37\24\2\0\65\24\1\0\7\24\1\0\1\24\3\0\3\24"+
    "\1\0\7\24\3\0\4\24\2\0\6\24\4\0\15\24\5\0\3\24"+
    "\1\0\7\24\16\0\5\25\32\0\5\25\20\0\2\24\23\0\1\24"+
    "\13\0\5\25\5\0\6\25\1\0\1\24\15\0\1\24\20\0\15\24"+
    "\3\0\33\24\25\0\15\25\4\0\1\25\3\0\14\25\21\0\1\24"+
    "\4\0\1\24\2\0\12\24\1\0\1\24\3\0\5\24\6\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\4\24\1\0\13\24\2\0\4\24"+
    "\5\0\5\24\4\0\1\24\21\0\51\24\u0a77\0\57\24\1\0\57\24"+
    "\1\0\205\24\6\0\4\24\3\25\2\24\14\0\46\24\1\0\1\24"+
    "\5\0\1\24\2\0\70\24\7\0\1\24\17\0\1\25\27\24\11\0"+
    "\7\24\1\0\7\24\1\0\7\24\1\0\7\24\1\0\7\24\1\0"+
    "\7\24\1\0\7\24\1\0\7\24\1\0\40\25\57\0\1\24\u01d5\0"+
    "\3\24\31\0\11\24\6\25\1\0\5\24\2\0\5\24\4\0\126\24"+
    "\2\0\2\25\2\0\3\24\1\0\132\24\1\0\4\24\5\0\51\24"+
    "\3\0\136\24\21\0\33\24\65\0\20\24\u0200\0\u19b6\24\112\0\u51cd\24"+
    "\63\0\u048d\24\103\0\56\24\2\0\u010d\24\3\0\20\24\12\25\2\24"+
    "\24\0\57\24\1\25\4\0\12\25\1\0\31\24\7\0\1\25\120\24"+
    "\2\25\45\0\11\24\2\0\147\24\2\0\4\24\1\0\4\24\14\0"+
    "\13\24\115\0\12\24\1\25\3\24\1\25\4\24\1\25\27\24\5\25"+
    "\20\0\1\24\7\0\64\24\14\0\2\25\62\24\21\25\13\0\12\25"+
    "\6\0\22\25\6\24\3\0\1\24\4\0\12\25\34\24\10\25\2\0"+
    "\27\24\15\25\14\0\35\24\3\0\4\25\57\24\16\25\16\0\1\24"+
    "\12\25\46\0\51\24\16\25\11\0\3\24\1\25\10\24\2\25\2\0"+
    "\12\25\6\0\27\24\3\0\1\24\1\25\4\0\60\24\1\25\1\24"+
    "\3\25\2\24\2\25\5\24\2\25\1\24\1\25\1\24\30\0\3\24"+
    "\2\0\13\24\5\25\2\0\3\24\2\25\12\0\6\24\2\0\6\24"+
    "\2\0\6\24\11\0\7\24\1\0\7\24\221\0\43\24\10\25\1\0"+
    "\2\25\2\0\12\25\6\0\u2ba4\24\14\0\27\24\4\0\61\24\u2104\0"+
    "\u016e\24\2\0\152\24\46\0\7\24\14\0\5\24\5\0\1\24\1\25"+
    "\12\24\1\0\15\24\1\0\5\24\1\0\1\24\1\0\2\24\1\0"+
    "\2\24\1\0\154\24\41\0\u016b\24\22\0\100\24\2\0\66\24\50\0"+
    "\15\24\3\0\20\25\20\0\7\25\14\0\2\24\30\0\3\24\31\0"+
    "\1\24\6\0\5\24\1\0\207\24\2\0\1\25\4\0\1\24\13\0"+
    "\12\25\7\0\32\24\4\0\1\24\1\0\32\24\13\0\131\24\3\0"+
    "\6\24\2\0\6\24\2\0\6\24\2\0\3\24\3\0\2\24\3\0"+
    "\2\24\22\0\3\25\4\0\14\24\1\0\32\24\1\0\23\24\1\0"+
    "\2\24\1\0\17\24\2\0\16\24\42\0\173\24\105\0\65\24\210\0"+
    "\1\25\202\0\35\24\3\0\61\24\57\0\37\24\21\0\33\24\65\0"+
    "\36\24\2\0\44\24\4\0\10\24\1\0\5\24\52\0\236\24\2\0"+
    "\12\25\u0356\0\6\24\2\0\1\24\1\0\54\24\1\0\2\24\3\0"+
    "\1\24\2\0\27\24\252\0\26\24\12\0\32\24\106\0\70\24\6\0"+
    "\2\24\100\0\1\24\3\25\1\0\2\25\5\0\4\25\4\24\1\0"+
    "\3\24\1\0\33\24\4\0\3\25\4\0\1\25\40\0\35\24\203\0"+
    "\66\24\12\0\26\24\12\0\23\24\215\0\111\24\u03b7\0\3\25\65\24"+
    "\17\25\37\0\12\25\20\0\3\25\55\24\13\25\2\0\1\25\22\0"+
    "\31\24\7\0\12\25\6\0\3\25\44\24\16\25\1\0\12\25\100\0"+
    "\3\25\60\24\16\25\4\24\13\0\12\25\u04a6\0\53\24\15\25\10\0"+
    "\12\25\u0936\0\u036f\24\221\0\143\24\u0b9d\0\u042f\24\u33d1\0\u0239\24\u04c7\0"+
    "\105\24\13\0\1\24\56\25\20\0\4\25\15\24\u4060\0\2\24\u2163\0"+
    "\5\25\3\0\26\25\2\0\7\25\36\0\4\25\224\0\3\25\u01bb\0"+
    "\125\24\1\0\107\24\1\0\2\24\2\0\1\24\2\0\2\24\2\0"+
    "\4\24\1\0\14\24\1\0\1\24\1\0\7\24\1\0\101\24\1\0"+
    "\4\24\2\0\10\24\1\0\7\24\1\0\34\24\1\0\4\24\1\0"+
    "\5\24\1\0\1\24\3\0\7\24\1\0\u0154\24\2\0\31\24\1\0"+
    "\31\24\1\0\37\24\1\0\31\24\1\0\37\24\1\0\31\24\1\0"+
    "\37\24\1\0\31\24\1\0\37\24\1\0\31\24\1\0\10\24\2\0"+
    "\62\25\u1600\0\4\24\1\0\33\24\1\0\2\24\1\0\1\24\2\0"+
    "\1\24\1\0\12\24\1\0\4\24\1\0\1\24\1\0\1\24\6\0"+
    "\1\24\4\0\1\24\1\0\1\24\1\0\1\24\1\0\3\24\1\0"+
    "\2\24\1\0\1\24\2\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\2\24\1\0\1\24\2\0\4\24\1\0"+
    "\7\24\1\0\4\24\1\0\4\24\1\0\1\24\1\0\12\24\1\0"+
    "\21\24\5\0\3\24\1\0\5\24\1\0\21\24\u1144\0\ua6d7\24\51\0"+
    "\u1035\24\13\0\336\24\u3fe2\0\u021e\24\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\25\36\0\140\25\200\0\360\25\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\2\3\1\1"+
    "\1\5\1\6\2\0\1\7\2\3\1\5\2\0\2\3"+
    "\1\0\1\10\1\11\33\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[52];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\27\0\56\0\27\0\105\0\134\0\163\0\212"+
    "\0\241\0\270\0\270\0\27\0\317\0\346\0\375\0\u0114"+
    "\0\u012b\0\27\0\u0142\0\u0159\0\u0170\0\u0187\0\u019e\0\27"+
    "\0\134\0\u01b5\0\u01cc\0\u01e3\0\u01fa\0\u0211\0\u0228\0\u023f"+
    "\0\u0256\0\u026d\0\u0284\0\u029b\0\u02b2\0\u02c9\0\u02e0\0\u02f7"+
    "\0\u030e\0\u0325\0\u033c\0\u0353\0\u036a\0\u0381\0\u0398\0\u03af"+
    "\0\u03c6\0\u03dd\0\u03f4\0\u040b";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[52];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\2\7\1\2\1\10"+
    "\3\6\1\11\3\6\2\12\1\13\1\6\2\2\31\0"+
    "\1\4\30\0\1\14\2\15\2\0\10\15\13\0\2\6"+
    "\2\0\10\6\1\16\2\0\2\6\11\0\1\17\23\0"+
    "\2\6\2\0\1\6\1\20\6\6\1\16\2\0\2\6"+
    "\6\0\2\6\2\0\5\6\1\21\2\6\1\16\2\0"+
    "\2\6\22\0\1\22\11\0\1\14\2\23\2\0\10\23"+
    "\13\0\1\24\3\0\10\24\3\0\1\24\10\0\1\17"+
    "\25\0\2\6\2\0\2\6\1\25\5\6\1\16\2\0"+
    "\2\6\6\0\2\6\2\0\6\6\1\26\1\6\1\16"+
    "\2\0\2\6\5\0\1\14\2\27\2\0\10\27\13\0"+
    "\2\24\2\0\10\24\3\0\2\24\1\30\5\0\2\6"+
    "\2\0\3\6\1\31\4\6\1\16\2\0\2\6\6\0"+
    "\2\6\2\0\7\6\1\25\1\16\2\0\2\6\5\0"+
    "\1\14\2\32\2\0\10\32\12\0\1\14\2\33\2\0"+
    "\10\33\12\0\1\14\2\34\2\0\10\34\12\0\1\14"+
    "\2\35\2\0\10\35\12\0\1\14\2\36\2\0\10\36"+
    "\12\0\1\14\2\37\2\0\10\37\12\0\1\14\2\40"+
    "\2\0\10\40\12\0\1\14\2\41\2\0\10\41\12\0"+
    "\1\14\2\42\2\0\10\42\12\0\1\14\2\43\2\0"+
    "\10\43\12\0\1\14\2\44\2\0\10\44\12\0\1\14"+
    "\2\45\2\0\10\45\12\0\1\14\2\46\2\0\10\46"+
    "\12\0\1\14\2\47\2\0\10\47\12\0\1\14\2\50"+
    "\2\0\10\50\12\0\1\14\2\51\2\0\10\51\12\0"+
    "\1\14\2\52\2\0\10\52\12\0\1\14\2\53\2\0"+
    "\10\53\12\0\1\14\2\54\2\0\10\54\12\0\1\14"+
    "\2\55\2\0\10\55\12\0\1\14\2\56\2\0\10\56"+
    "\12\0\1\14\2\57\2\0\10\57\12\0\1\14\2\60"+
    "\2\0\10\60\12\0\1\14\2\61\2\0\10\61\12\0"+
    "\1\14\2\62\2\0\10\62\12\0\1\14\2\63\2\0"+
    "\10\63\12\0\1\14\2\64\2\0\10\64\12\0\1\14"+
    "\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1058];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\7\1\1\11\2\0\3\1"+
    "\1\11\2\0\2\1\1\0\1\11\1\1\33\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[52];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2810) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.print(yytext());
            } 
            // fall through
          case 10: break;
          case 2: 
            { /* ignore */
            } 
            // fall through
          case 11: break;
          case 3: 
            { System.out.printf("\n>>> Identificador encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
            } 
            // fall through
          case 12: break;
          case 4: 
            { System.out.printf("\n>>> Integer encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
            } 
            // fall through
          case 13: break;
          case 5: 
            { System.out.printf(">>> Operador encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
            } 
            // fall through
          case 14: break;
          case 6: 
            { System.out.printf("\n>>> String encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
            } 
            // fall through
          case 15: break;
          case 7: 
            { System.out.printf("\n>>> Double encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
            } 
            // fall through
          case 16: break;
          case 8: 
            { System.out.printf("\n>>> Sentencia encontrada: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
            } 
            // fall through
          case 17: break;
          case 9: 
            { System.out.printf("\n>>> Bool encontrado: [%s] en linea %d, columna %d\n", yytext(), yyline, yycolumn);
            } 
            // fall through
          case 18: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
