
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENDDECLARE_SECTION = 29;
  public static final int DISTINTO = 7;
  public static final int PUNTO_Y_COMA = 5;
  public static final int PARENTESIS_CIERRA = 13;
  public static final int RESTA = 19;
  public static final int DOS_PUNTOS = 2;
  public static final int CONST_INTEGER = 38;
  public static final int AND = 16;
  public static final int IGUAL = 6;
  public static final int OR = 17;
  public static final int SUMA = 18;
  public static final int CONST_FLOAT = 39;
  public static final int IF = 26;
  public static final int ID = 36;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int MODULO = 22;
  public static final int LLAVES_CIERRA = 15;
  public static final int MENOR = 9;
  public static final int CONST_BOOL = 40;
  public static final int TYPE_FLOAT = 34;
  public static final int ASIGNACION = 4;
  public static final int MAYOR = 8;
  public static final int ELSE = 27;
  public static final int TYPE_INTEGER = 33;
  public static final int TYPE_STRING = 32;
  public static final int WHILE = 25;
  public static final int MAYOR_IGUAL = 10;
  public static final int CONST_STRING = 37;
  public static final int PROGRAM_SECTION = 30;
  public static final int IF_UNARIO = 23;
  public static final int ENDPROGRAM_SECTION = 31;
  public static final int MENOR_IGUAL = 11;
  public static final int TYPE_BOOL = 35;
  public static final int DISPLAY_FUNCTION = 24;
  public static final int DIVISION = 20;
  public static final int MULTIPLICAION = 21;
  public static final int PARENTESIS_ABRE = 12;
  public static final int LLAVES_ABRE = 14;
  public static final int DECLARE_SECTION = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOS_PUNTOS",
  "COMA",
  "ASIGNACION",
  "PUNTO_Y_COMA",
  "IGUAL",
  "DISTINTO",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "LLAVES_ABRE",
  "LLAVES_CIERRA",
  "AND",
  "OR",
  "SUMA",
  "RESTA",
  "DIVISION",
  "MULTIPLICAION",
  "MODULO",
  "IF_UNARIO",
  "DISPLAY_FUNCTION",
  "WHILE",
  "IF",
  "ELSE",
  "DECLARE_SECTION",
  "ENDDECLARE_SECTION",
  "PROGRAM_SECTION",
  "ENDPROGRAM_SECTION",
  "TYPE_STRING",
  "TYPE_INTEGER",
  "TYPE_FLOAT",
  "TYPE_BOOL",
  "ID",
  "CONST_STRING",
  "CONST_INTEGER",
  "CONST_FLOAT",
  "CONST_BOOL"
  };
}

